# Generated by Django 5.2.4 on 2025-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tags",
            new_name="tag",
        ),
        migrations.AddField(
            model_name="post",
            name="click_num",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
