# Generated by Django 5.2.4 on 2025-08-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_rename_tags_post_tag_post_click_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tag",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="post.tag"
            ),
        ),
    ]
