# Generated by Django 5.2.4 on 2025-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remove_post_tag_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="click_num",
        ),
        migrations.AddField(
            model_name="post",
            name="like_cnt",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
